[profile.default]
solc-version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000

gas_reports = [
    "CrateFactoryV1",
    "CrateTokenV1"
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]